### PR TITLE
Location Permission feature setups and implementations for PetShop

### PR DESCRIPTION
**Pull request by EmmanuelTobi**
Love this project and its UI design, and this is me making my contributions to it...and more to come too.

pub libs updated with geolocation, geolocator and permission handler.

Created and added permission handler in the util folder to handle any required permission setup.

Implemented location check and request permission in the security section of Settings while also updating the Container to Column. Couldn't add a nice location icon but could added if you merge the changes.

Next will be getting user's location address and doing more checks.

### CODE REVIEW

**Comment by thenifemi** [comment]
Alright, this is nice, thanks.

**Comment by EmmanuelTobi** [comment]
Hello, hope you are doing good.

Still available to help out with two or three issues in case you wanna fill
me in. I saw the swipe to remove feature, but yet to be implemented. wanna
know if you are working on it. Also the location address thing will require
you staging your project to firebase blaze plan if you haven't.

Nice work you putting to it.

**Comment by thenifemi** [comment]
@EmmanuelTobi Hey, Yeah, I'm working on the 'swipe to remove' feature. Can you please tell me another way you'd like to help in..

**Comment by EmmanuelTobi** [comment]
Maybe you can create some list of issues properly this time and each will be correlated to any PR when taken on.

**Comment by thenifemi** [comment]
Alright, I will do that.

**Pull request merged**
